---
swagger: "2.0"
info:
  description: "a standard restful api for project react-antd-admin"
  version: "0.0.0"
  title: "React AntD Admin Rest Api"
host: "localhost:30000"
basePath: "/api/v1"
tags:
- name: "user"
  description: "Everything about your Pets"
- name: "authentication"
  description: "authentication"
schemes:
- "http"
- "https"
paths:
  /authentication:
    post:
      tags:
      - "authentication"
      summary: "post username and password"
      description: "Will send the authenticated user info if authentication is succesful,\
        \ otherwise it will send `Authentication failed`"
      operationId: "postAuthentication"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      - "text/plain"
      - "text/html"
      parameters:
      - in: "body"
        name: "userInfo"
        description: "user info for authenticate"
        required: true
        schema:
          $ref: "#/definitions/userInfo"
      responses:
        200:
          description: "authenticated user info"
          schema:
            $ref: "#/definitions/inline_response_200"
          examples:
            application/json:
              id: "10000"
              name: "Running Coder"
              token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxMDAwMCIsImV4cCI6MzAwMDAwLCJhdWQiOiJ2aXNpdG9yIiwic3ViIjoiaHR0cDovL3JlYWN0LWFudGQtYWRtaW4tc2VydmVyIiwiaXNzIjoicmVhY3QtYW50ZC1hZG1pbi1zZXJ2ZXIiLCJuYmYiOjE1MDY1MzI1MTcsImlhdCI6MTUwNjUzMjU2MCwianRpIjoiMjU2ZGY0NzMtYzBjZS00ZjhiLTk5ZTYtODA1Njk3MzJjNjYxIn0.DiRZgh70EDIZQSQbkHCrXigQW0gmNBzmY6A-uOt0jfQ"
          headers:
            api-key:
              type: "string"
              description: "authenticated token"
        400:
          description: "bad request"
        500:
          description: "internal server error"
      x-swagger-router-controller: "Authentication"
  /billionaires:
    get:
      tags:
      - "billionaires"
      summary: "list of the world's billionaires"
      description: "get top ten billionaires in the world"
      operationId: "billionairesGET"
      parameters: []
      responses:
        200:
          description: "OK"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/inline_response_200_1"
          examples:
            application/json:
            - name: "Bill Gates"
              ranking:
                number: 1
                trend: "steady"
              netWorth:
                value: "$86.0 billion"
                trend: "increase"
              age: 61
              nationality: "USA"
              sourceOfWealth: "Microsoft"
            - name: "Warren Buffett"
              ranking:
                number: 2
                trend: "increase"
              netWorth:
                value: "$75.6 billion"
                trend: "increase"
              age: 86
              nationality: "USA"
              sourceOfWealth: "Berkshire Hathaway"
        400:
          description: "badrequset"
        500:
          description: "internal server error"
      security:
      - api_key: []
      x-swagger-router-controller: "Billionaires"
securityDefinitions:
  api_key:
    type: "apiKey"
    name: "api-key"
    in: "header"
definitions:
  userInfo:
    type: "object"
    required:
    - "password"
    - "username"
    properties:
      username:
        type: "string"
      password:
        type: "string"
  billionaires_ranking:
    properties:
      number:
        type: "integer"
      trend:
        type: "string"
        enum:
        - "increase"
        - "decrease"
        - "steady"
  inline_response_200_1:
    properties:
      name:
        type: "string"
      ranking:
        $ref: "#/definitions/billionaires_ranking"
      netWorth:
        $ref: "#/definitions/billionaires_netWorth"
      age:
        type: "integer"
      nationality:
        type: "string"
      sourceOfWealth:
        type: "string"
  inline_response_200:
    properties:
      id:
        type: "string"
      name:
        type: "string"
      token:
        type: "string"
  billionaires_netWorth:
    properties:
      value:
        type: "string"
      trend:
        type: "string"
        enum:
        - "increase"
        - "decrease"
        - "steady"
