---
swagger: "2.0"
info:
  description: "a standard restful api for project react-antd-admin"
  version: "0.0.0"
  title: "React AntD Admin Rest Api"
host: "localhost:30000"
basePath: "/api/v1"
tags:
- name: "user"
  description: "Everything about your Pets"
- name: "authentication"
  description: "authentication"
schemes:
- "http"
- "https"
paths:
  /authentication:
    post:
      tags:
      - "authentication"
      summary: "post username and password"
      description: "Will send the authenticated user info if authentication is succesful,\
        \ otherwise it will send `Authentication failed`"
      operationId: "postAuthentication"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      - "text/plain"
      parameters:
      - in: "body"
        name: "userInfo"
        description: "user info for authenticate"
        required: true
        schema:
          $ref: "#/definitions/userInfo"
      responses:
        200:
          description: "authenticated user info"
          schema:
            $ref: "#/definitions/inline_response_200"
          examples:
            application/json:
              name: "mock-admin"
              token: "mock-token"
        400:
          description: "bad request"
        500:
          description: "internal server error"
      x-swagger-router-controller: "Authentication"
definitions:
  userInfo:
    type: "object"
    required:
    - "username"
    properties:
      username:
        type: "string"
      password:
        type: "string"
  inline_response_200:
    properties:
      name:
        type: "string"
      token:
        type: "string"
