swagger: '2.0'

info:
  version: 0.0.0
  title: React AntD Admin Rest Api
  description: a standard restful api for project react-antd-admin
  
host: 'localhost:30000'
basePath: /api/v1

tags:
- name: user
  description: Everything about your Pets
- name: authentication
  description: authentication
    
schemes:
- http
- https
  
paths:
  /authentication:
    post:
      tags:
      - authentication
      summary: post username and password
      description: Will send the authenticated user info if authentication is succesful, otherwise
            it will send `Authentication failed`
      consumes:
      - application/json
      produces:
      - application/json
      - text/plain
      operationId: postAuthentication
      parameters:
      - name: userInfo
        in: body
        description: user info for authenticate
        required: true
        schema: 
          required: 
          - username
          type: object
          properties:
            username:
              type: string
            password:
              type: string
      responses:
        '200':
          description: authenticated user info 
          schema: 
            type: object
            properties:
              name: 
                type: string
              token:
                type: string
          examples:
            application/json:
              name: 'mock-admin'
              token: 'mock-token'
        '400':
          description: bad request
        '500':
          description: internal server error
