swagger: '2.0'

info:
  version: 0.0.0
  title: React-Antd-Admin-Rest-Api
  description: a standard restful api for project react-antd-admin
  
host: 'localhost:30000'
basePath: /api/v1

tags:
- name: user
  description: Everything about your Pets
- name: authentication
  description: authentication
    
schemes:
- http
- https

securityDefinitions:
  api_key:
    type: apiKey
    name: api-key
    in: header
    
 
  
paths:
  /authentication:
    post:
      tags:
      - authentication
      summary: post username and password
      description: Will send the authenticated user info if authentication is succesful, otherwise
            it will send `Authentication failed`
      consumes:
      - application/json
      produces:
      - application/json
      - text/plain
      - text/html
      operationId: postAuthentication
      parameters:
      - name: userInfo
        in: body
        description: user info for authenticate
        required: true
        schema: 
          required: 
          - username
          - password
          type: object
          properties:
            username:
              type: string
            password:
              type: string
      responses:
        200:
          description: authenticated user info 
          headers:
            api-key:
              type: string
              description: authenticated token
          schema: 
            type: object
            properties:
              id: 
                type: string
              name: 
                type: string
              token:
                type: string
          examples:
            application/json:
              id: '10000'
              name: 'Running Coder'
              token: 'xxxxxxxxxx'
        400:
          description: bad request
        500:
          description: internal server error
  /billionaires:
    get:
      tags: 
      - billionaires
      summary: list of the world's billionaires
      description: get top ten billionaires in the world
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              type: object
              properties:
                name:
                  type: string
                ranking:
                  type: object
                  properties:
                    number:
                      type: integer
                    trend:
                      type: string
                      enum: 
                      - increase
                      - decrease
                      - steady
                netWorth:
                  type: object
                  properties:
                    value:
                      type: string
                    trend:
                      type: string
                      enum: 
                      - increase
                      - decrease
                      - steady
                age: 
                  type: integer
                nationality:
                  type: string
                sourceOfWealth:
                  type: string
          examples: 
            application/json:
            - name: Bill Gates
              ranking: 
                number: 1
                trend: steady
              netWorth:
                value: $86.0 billion
                trend: increase
              age: 61
              nationality: USA
              sourceOfWealth: Microsoft
            - name: Warren Buffett
              ranking: 
                number: 2
                trend: increase
              netWorth:
                value: $75.6 billion
                trend: increase
              age: 86
              nationality: USA
              sourceOfWealth: Berkshire Hathaway
        400:
          description: badrequset
        500:
          description: internal server error
      security: 
      - api_key: []
    
